[package]
name = "tseitin"
version = "0.0.1"
authors = ["Leon Frangen"]
edition = "2021"
publish = false

[dependencies]
rust-sitter =  "0.3.4"
codemap = "0.1.2"
#codemap-diagnostic = { version = "0.1.2" }

[build-dependencies]
rust-sitter-tool = "0.3.4"
