[package]
name = "tseitin"
version = "0.0.1"
authors = ["Leon Frangen"]
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }

#[build-dependencies]
#rust-sitter-tool = "0.4.1"
